// ── Config Registry: defines editable runtime config keys per service ────────

export type ConfigValueType = 'number' | 'string' | 'boolean' | 'float'

export interface ConfigKeySchema {
  key: string
  label: string
  description: string
  type: ConfigValueType
  defaultValue: string
  group: string
  validation?: { min?: number; max?: number; pattern?: string }
}

export interface ServiceConfigSchema {
  serviceId: string
  displayName: string
  k8sServiceName: string
  k8sServicePort: number
  configMapName: string
  namespace: string
  keys: ConfigKeySchema[]
}

const NAMESPACE = 'graph-foundry-system'

export const SERVICE_CONFIG_REGISTRY: ServiceConfigSchema[] = [
  {
    serviceId: 'service-graph-engine',
    displayName: 'Service Graph Engine',
    k8sServiceName: 'service-graph-engine',
    k8sServicePort: 3000,
    configMapName: 'service-graph-engine-runtime',
    namespace: NAMESPACE,
    keys: [
      {
        key: 'OVERVIEW_NAMESPACE',
        label: 'Overview Namespace',
        description: 'Kubernetes namespace to monitor for service discovery and graph building',
        type: 'string',
        defaultValue: 'default',
        group: 'General',
      },
      {
        key: 'POLL_INTERVAL_Ms',
        label: 'Poll Interval',
        description: 'Telemetry polling interval in milliseconds',
        type: 'number',
        defaultValue: '30000',
        group: 'Polling',
        validation: { min: 1000, max: 600000 },
      },
      {
        key: 'SCORE_CALCULATION_INTERVAL_Ms',
        label: 'Score Calculation Interval',
        description: 'PageRank/betweenness score recalculation interval in milliseconds',
        type: 'number',
        defaultValue: '120000',
        group: 'Polling',
        validation: { min: 2000, max: 3600000 },
      },
    ],
  },
  {
    serviceId: 'analysis-engine',
    displayName: 'Analysis Engine',
    k8sServiceName: 'analysis-engine',
    k8sServicePort: 7000,
    configMapName: 'analysis-engine-runtime',
    namespace: NAMESPACE,
    keys: [
      {
        key: 'OVERVIEW_NAMESPACE',
        label: 'Overview Namespace',
        description: 'Kubernetes namespace to monitor for service discovery and graph building',
        type: 'string',
        defaultValue: 'default',
        group: 'General',
      },
      {
        key: 'MAX_TRAVERSAL_DEPTH',
        label: 'Max Traversal Depth',
        description: 'Maximum depth for dependency graph traversal in simulations',
        type: 'number',
        defaultValue: '2',
        group: 'Simulation',
        validation: { min: 1, max: 10 },
      },
      {
        key: 'SCALING_MODEL',
        label: 'Scaling Model',
        description: 'Latency scaling model (bounded_sqrt, linear, exponential)',
        type: 'string',
        defaultValue: 'bounded_sqrt',
        group: 'Simulation',
      },
      {
        key: 'SCALING_ALPHA',
        label: 'Scaling Alpha',
        description: 'Alpha parameter for the scaling model',
        type: 'float',
        defaultValue: '0.5',
        group: 'Simulation',
        validation: { min: 0.01, max: 2.0 },
      },
      {
        key: 'MIN_LATENCY_FACTOR',
        label: 'Min Latency Factor',
        description: 'Minimum latency multiplication factor during simulation',
        type: 'float',
        defaultValue: '0.6',
        group: 'Simulation',
        validation: { min: 0.1, max: 1.0 },
      },
      {
        key: 'TIMEOUT_MS',
        label: 'Simulation Timeout',
        description: 'Timeout for simulation operations in milliseconds',
        type: 'number',
        defaultValue: '8000',
        group: 'Simulation',
        validation: { min: 1000, max: 60000 },
      },
      {
        key: 'MAX_PATHS_RETURNED',
        label: 'Max Paths Returned',
        description: 'Maximum number of dependency paths returned in simulation results',
        type: 'number',
        defaultValue: '10',
        group: 'Simulation',
        validation: { min: 1, max: 100 },
      },
      {
        key: 'SHARED_HOST_RESOURCES',
        label: 'Shared Host Resources',
        description: 'Account for shared host resource contention in simulations',
        type: 'boolean',
        defaultValue: 'false',
        group: 'Simulation',
      },
      {
        key: 'RATE_LIMIT_WINDOW_MS',
        label: 'Rate Limit Window',
        description: 'Rate limiting window in milliseconds',
        type: 'number',
        defaultValue: '60000',
        group: 'Rate Limiting',
        validation: { min: 1000, max: 600000 },
      },
      {
        key: 'RATE_LIMIT_MAX',
        label: 'Rate Limit Max Requests',
        description: 'Maximum requests allowed per rate limit window',
        type: 'number',
        defaultValue: '60',
        group: 'Rate Limiting',
        validation: { min: 1, max: 10000 },
      },
      {
        key: 'TELEMETRY_POLL_INTERVAL_MS',
        label: 'Telemetry Poll Interval',
        description: 'How often the telemetry worker polls for new data in milliseconds',
        type: 'number',
        defaultValue: '60000',
        group: 'Telemetry',
        validation: { min: 5000, max: 600000 },
      },
      {
        key: 'WEBHOOK_FORWARD_RETRY_MAX',
        label: 'Webhook Forward Max Retries',
        description: 'Maximum number of retries for forwarding webhooks',
        type: 'number',
        defaultValue: '5',
        group: 'Webhook',
        validation: { min: 0, max: 20 },
      },
      {
        key: 'WEBHOOK_FORWARD_RETRY_BASE_DELAY_MS',
        label: 'Webhook Retry Base Delay',
        description: 'Base delay for webhook retry backoff in milliseconds',
        type: 'number',
        defaultValue: '250',
        group: 'Webhook',
        validation: { min: 50, max: 10000 },
      },
      {
        key: 'WEBHOOK_FORWARD_RETRY_MAX_DELAY_MS',
        label: 'Webhook Retry Max Delay',
        description: 'Maximum delay between webhook retry attempts in milliseconds',
        type: 'number',
        defaultValue: '5000',
        group: 'Webhook',
        validation: { min: 500, max: 60000 },
      },
      {
        key: 'WEBHOOK_MAX_IN_FLIGHT',
        label: 'Webhook Max In-Flight',
        description: 'Maximum number of concurrent webhook forward requests',
        type: 'number',
        defaultValue: '32',
        group: 'Webhook',
        validation: { min: 1, max: 256 },
      },
      {
        key: 'WEBHOOK_PROCESS_TIMEOUT_MS',
        label: 'Webhook Process Timeout',
        description: 'Timeout for processing a single webhook event in milliseconds',
        type: 'number',
        defaultValue: '15000',
        group: 'Webhook',
        validation: { min: 1000, max: 120000 },
      },
    ],
  },
  {
    serviceId: 'graph-alert-engine',
    displayName: 'Graph Alert Engine',
    k8sServiceName: 'graph-alert-engine',
    k8sServicePort: 8002,
    configMapName: 'graph-alert-engine-runtime',
    namespace: NAMESPACE,
    keys: [
      {
        key: 'GRAPH_TIMEOUT_MS',
        label: 'Graph API Timeout',
        description: 'Timeout for graph service API calls in milliseconds',
        type: 'number',
        defaultValue: '2000',
        group: 'Graph Client',
        validation: { min: 500, max: 30000 },
      },
      {
        key: 'GRAPH_RETRY_MAX',
        label: 'Graph API Max Retries',
        description: 'Maximum number of retries for graph service API calls',
        type: 'number',
        defaultValue: '2',
        group: 'Graph Client',
        validation: { min: 0, max: 10 },
      },
      {
        key: 'CENTRALITY_CACHE_TTL_MS',
        label: 'Centrality Cache TTL',
        description: 'Time-to-live for cached centrality scores in milliseconds',
        type: 'number',
        defaultValue: '30000',
        group: 'Graph Client',
        validation: { min: 5000, max: 600000 },
      },
      {
        key: 'RISK_W1',
        label: 'Risk Weight: PageRank',
        description: 'Weight for PageRank centrality in risk score calculation',
        type: 'float',
        defaultValue: '1.0',
        group: 'Risk Assessment',
        validation: { min: 0.0, max: 10.0 },
      },
      {
        key: 'RISK_W2',
        label: 'Risk Weight: Latency',
        description: 'Weight for latency in risk score calculation',
        type: 'float',
        defaultValue: '1.0',
        group: 'Risk Assessment',
        validation: { min: 0.0, max: 10.0 },
      },
      {
        key: 'RISK_W3',
        label: 'Risk Weight: Error Rate',
        description: 'Weight for error rate in risk score calculation',
        type: 'float',
        defaultValue: '1.0',
        group: 'Risk Assessment',
        validation: { min: 0.0, max: 10.0 },
      },
      {
        key: 'RISK_THRESHOLD',
        label: 'Risk Threshold',
        description: 'Risk score threshold above which alerts are generated',
        type: 'float',
        defaultValue: '60.0',
        group: 'Risk Assessment',
        validation: { min: 0.0, max: 100.0 },
      },
      {
        key: 'SLACK_WEBHOOK_URL',
        label: 'Slack Webhook URL',
        description:
          'Incoming webhook URL for Slack notifications. When set, alerts are pushed to Slack. Leave empty to disable.',
        type: 'string',
        defaultValue: '',
        group: 'Integrations',
      },
      {
        key: 'DASHBOARD_URL',
        label: 'Dashboard URL',
        description:
          'External URL of the integrated dashboard. Used in Slack alerts to link back to the alert detail page.',
        type: 'string',
        defaultValue: '',
        group: 'Integrations',
      },
    ],
  },
  {
    serviceId: 'best-node-selector',
    displayName: 'Best Node Selector',
    k8sServiceName: 'best-node-selector',
    k8sServicePort: 9000,
    configMapName: 'best-node-selector-runtime',
    namespace: NAMESPACE,
    keys: [
      {
        key: 'TIME_WINDOW_SECONDS',
        label: 'Metrics Time Window',
        description: 'Time window in seconds for metrics aggregation',
        type: 'number',
        defaultValue: '10',
        group: 'Scoring',
        validation: { min: 1, max: 300 },
      },
      {
        key: 'TOPK_PEERS',
        label: 'Top-K Peers',
        description: 'Number of top peer services to consider for scoring',
        type: 'number',
        defaultValue: '1',
        group: 'Scoring',
        validation: { min: 1, max: 20 },
      },
      {
        key: 'ENABLE_SCORE_UPDATE',
        label: 'Enable Score Updates',
        description: 'Enable/disable the background scoring loop',
        type: 'boolean',
        defaultValue: 'true',
        group: 'Scoring',
      },
      {
        key: 'SCORER_INTERVAL_SEC',
        label: 'Scorer Interval',
        description: 'How often scores are recalculated in seconds',
        type: 'number',
        defaultValue: '10',
        group: 'Scoring',
        validation: { min: 1, max: 300 },
      },
      {
        key: 'REBALANCING_ENABLED',
        label: 'Rebalancing Enabled',
        description: 'Enable/disable automatic pod rebalancing',
        type: 'boolean',
        defaultValue: 'true',
        group: 'Rebalancing',
      },
      {
        key: 'REBALANCE_INTERVAL_SECONDS',
        label: 'Rebalance Interval',
        description: 'How often the rebalancer runs in seconds',
        type: 'number',
        defaultValue: '300',
        group: 'Rebalancing',
        validation: { min: 30, max: 3600 },
      },
      {
        key: 'REBALANCE_COOLDOWN_SECONDS',
        label: 'Rebalance Cooldown',
        description: 'Cooldown period after a rebalance cycle in seconds',
        type: 'number',
        defaultValue: '1800',
        group: 'Rebalancing',
        validation: { min: 60, max: 7200 },
      },
      {
        key: 'LATENCY_THRESHOLD_MS',
        label: 'Latency Threshold',
        description: 'Latency threshold in milliseconds that triggers rebalancing',
        type: 'float',
        defaultValue: '40',
        group: 'Rebalancing',
        validation: { min: 1, max: 10000 },
      },
      {
        key: 'MAX_PODS_MOVED_PER_CYCLE',
        label: 'Max Pods Moved Per Cycle',
        description: 'Maximum number of pods moved in a single rebalance cycle',
        type: 'number',
        defaultValue: '3',
        group: 'Rebalancing',
        validation: { min: 1, max: 20 },
      },
      {
        key: 'MAX_REBALANCE_DURATION_SECONDS',
        label: 'Max Rebalance Duration',
        description: 'Maximum duration of a rebalance cycle in seconds',
        type: 'number',
        defaultValue: '30',
        group: 'Rebalancing',
        validation: { min: 5, max: 300 },
      },
      {
        key: 'MIN_POD_AGE_FOR_REBALANCE_SECONDS',
        label: 'Min Pod Age for Rebalance',
        description: 'Minimum age of a pod before it can be rebalanced in seconds',
        type: 'number',
        defaultValue: '600',
        group: 'Rebalancing',
        validation: { min: 60, max: 7200 },
      },
      {
        key: 'POD_REBALANCE_ANTITHRASH_SECONDS',
        label: 'Pod Anti-Thrash Window',
        description: 'Minimum time between moves for the same pod in seconds',
        type: 'number',
        defaultValue: '3600',
        group: 'Rebalancing',
        validation: { min: 300, max: 86400 },
      },
    ],
  },
  {
    serviceId: 'dashboard-bff',
    displayName: 'Dashboard BFF',
    k8sServiceName: 'dashboard-bff',
    k8sServicePort: 3001,
    configMapName: 'dashboard-bff-runtime',
    namespace: NAMESPACE,
    keys: [
      {
        key: 'WEBHOOK_REPLAY_WINDOW_SEC',
        label: 'Webhook Replay Window',
        description: 'Maximum age in seconds for accepting webhook replays',
        type: 'number',
        defaultValue: '300',
        group: 'Webhook Security',
        validation: { min: 30, max: 3600 },
      },
      {
        key: 'WEBHOOK_DEDUPE_WINDOW_SEC',
        label: 'Webhook Dedup Window',
        description: 'Window in seconds for deduplicating webhook events',
        type: 'number',
        defaultValue: '86400',
        group: 'Webhook Security',
        validation: { min: 300, max: 604800 },
      },
      {
        key: 'WEBHOOK_RATE_LIMIT_WINDOW_MS',
        label: 'Rate Limit Window',
        description: 'Rate limiting window in milliseconds for incoming webhooks',
        type: 'number',
        defaultValue: '60000',
        group: 'Rate Limiting',
        validation: { min: 1000, max: 600000 },
      },
      {
        key: 'WEBHOOK_RATE_LIMIT_MAX',
        label: 'Rate Limit Max',
        description: 'Maximum webhook requests per rate limit window',
        type: 'number',
        defaultValue: '120',
        group: 'Rate Limiting',
        validation: { min: 1, max: 10000 },
      },
      {
        key: 'OPENAI_API_KEY',
        label: 'OpenAI API Key',
        description: 'API key used to summarize alert payloads before SMS delivery',
        type: 'string',
        defaultValue: '',
        group: 'Notifications',
      },
      {
        key: 'FITSMS_API_KEY',
        label: 'FitSMS API Key',
        description: 'Bearer token used to send SMS alerts through FitSMS',
        type: 'string',
        defaultValue: '',
        group: 'Notifications',
      },
      {
        key: 'FITSMS_API_URL',
        label: 'FitSMS API URL',
        description: 'HTTP endpoint for the FitSMS send API',
        type: 'string',
        defaultValue: 'https://app.fitsms.lk/api/v3/sms/send',
        group: 'Notifications',
      },
    ],
  },
]

export function getServiceSchema(serviceId: string): ServiceConfigSchema | undefined {
  return SERVICE_CONFIG_REGISTRY.find((s) => s.serviceId === serviceId)
}
